### ISSUE TITLE
Huh?! getPlayerFromId problem

### ISSUE THREAD

**Issue by iNoOx** [ldlac/foodhud_externals#1]
Hey, thank's for your work but i got a little problem... when i try to buy a item in stores, i got this error on the console:

http://i.imgur.com/EkfXza9.png

And i don't know why this error appears.. x')

EDIT: Sorry i'm an idiot.. XD just forgot to change itemID in foodGUI u_u

**Comment by ldlac** [comment]
Perfect then :) !

**Comment by iNoOx** [comment]
Little question, do you know why frfuel doesn't work on the first connection ? I have to relog into the server to see it  ?

**Comment by ldlac** [comment]
Good question, I don't know. I will try to search for this.

**Comment by iNoOx** [comment]
Thank's dude :)

Oh edit: The error is now here again when we are two or + on the server, work perfectly alone but no with other people :(

There is a problem with "getPlayerFromId", don't know if something is broken since yesterday but it's the first time i got this error :/

**Comment by ldlac** [comment]
I pushed a new version! Try it out

**Comment by iNoOx** [comment]
Thank's dude a lot, but sorry to say that... same error "getPlayerFromId" :( ^^

**Comment by iNoOx** [comment]
Now, we are two on the serveur, only one person can buy it for the first time, since other one try to buy one item > error on console

FR (si tu comprends): En gros là on est plusieurs sur le serveur, le premier qui achète les items tout fonctionne bien mais dès qu'un autre gars vient acheter, ça met une erreur avec le "getPlayerFromId" d'essentialmode :/

**Comment by ldlac** [comment]
Je viens de push une nouvelle version qui j'espère devrait fix le bug, j'ai repensé le code serveur de gb_foodshops, donc en principe ça devrait aller mieux! Donne moi des nouvelles!

**Comment by 4xx22** [comment]
Je me permet de rejoindre cette issues, j'ai aussi un problème, j'ai tenter avant et après le nouveau push ;) 
![yy4sz1s](https://cloud.githubusercontent.com/assets/17505454/26284447/b969e972-3e3b-11e7-9330-b549dbcc30fc.png)

**Comment by ldlac** [comment]
DefaltNF je crois que tu as simplement quelque chose de mal configuré je vais tenter de faire en sorte qu'il est moins de chose à entrer manuellement mais revérifie

**Comment by 4xx22** [comment]
@ldlac Effectivement, j'ai fait une petite faute de frappe, désoler du dérangement ^^

**Comment by ldlac** [comment]
J'ai testé à deux sur un serveur. Et tout fonctionnait. J'attends d'avoir plus de retour avant de confirmer le fix

**Comment by iNoOx** [comment]
Salut @ldlac, je choppe deux trois personnes pour essayer ton nouveau script et je te donne un retour ;)

**Comment by iNoOx** [comment]
Retour: Achat / Utilisation fonctionne parfaitement même à plusieurs joueurs (même la drogue, c'est fou :O).
Par contre, si il nous reste 1 bouteille d'eau et/ou 1 sandwich dans l'inventaire, lorsqu'on le mange, deux requêtes SQL se font, un avec un update dans l'user_inventory pour retirer les items consommés et direct derrière une autre pour remettre l'item consommé dans l'inventaire.
Et toujours le bug qui n'active pas FrFuel à la première connexion au serveur (réapparait après déco/reco).

Merci pour la correction en tout cas, ça déchire ! ;)

**Comment by ldlac** [comment]
Ok je regarde pour le truc d'un seul item, merci de la remarque!
Et merci aussi pour l'info de FrFuel, c'est une bonne piste!

**Comment by iNoOx** [comment]
Pas d'soucis, normal qu'on te donne tous les retours pour ce que tu fais, ça déchire ! ;)

**Comment by ldlac** [comment]
Le bug qu'il reste une seule bouteille et tout est réglé! Récupère la nouvelle version
Toujours assez flou du côté de frfuel qui ne fonctionne pas toujours.

**Comment by iNoOx** [comment]
Ah dément, par contre ouais, je sais pas pourquoi mais à la première connexion, pas de FrFuel, une déco/reco et tout apparaît.. x')

Merci en tout cas ! (y)

**Comment by ldlac** [comment]
FrFuel devrait être fix avec la nouvelle version du lien de foodhud! :)

**Comment by iNoOx** [comment]
J'ai vu ton post sur FiveM, bravo à toi ! :)
