### ISSUE TITLE
Good Job

### ISSUE THREAD

**Issue by Matheo2778** [ldlac/foodhud_externals#4]
Realy nice job but can you update vdk_invenory with new version pls ?

**Comment by iNoOx** [comment]
Yop @ldlac, ouais y'a eu une nouvelle version, j'ai passé 2 heures a essayé d'adapter le système complet (gb_foodshop, Coffeemachine) mais ça fonctionne plus quand tu utilise le use de vdk_inventory, même si tu met le use d'avant ><
